const $=(s:string)=>document.querySelector(s) as HTMLElement;
let batches:any[]=[],signature='',review:any=null;
const filter=$('#creative-filter') as HTMLSelectElement;
const dialog=$('#review-dialog') as HTMLDialogElement,player=$('#review-video') as HTMLVideoElement;
function node(tag:string,text:string,cls=''){const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;}
function link(text:string,href:string,cls='ui-button secondary'){const a=node('a',text,cls) as HTMLAnchorElement;a.href=href;return a;}
function editUrl(b:any,i:any){return '/editor?'+new URLSearchParams({video:i.source_id,batch:b.id,clip:i.clip_id});}
async function action(payload:any){const r=await fetch('/api/creatives',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw Error(data.error);return data;}
function openReview(b:any,item:any,index:number){review={...item,batchId:b.id};$('#review-title').textContent=`Criativo ${index+1} · @${item.profile||'perfil'}`;$('#review-subtitle').textContent=b.name;player.src='/api/media?kind=clip&id='+item.clip_id;($('#download-review') as HTMLAnchorElement).href=player.src+'&download=1';($('#edit-review') as HTMLAnchorElement).href=editUrl(b,item);$('#approve-review').textContent=item.approved?'Retirar aprovação':'Marcar como aprovado';$('#review-message').textContent=item.approved?'Aprovado. Pronto para baixar e publicar por conta própria.':'Confira o vídeo inteiro. Se precisar, ajuste no editor.';dialog.showModal();}
$('#close-review').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{player.pause();player.removeAttribute('src');player.load();review=null;});
$('#approve-review').addEventListener('click',async()=>{if(!review)return;const button=$('#approve-review') as HTMLButtonElement;button.disabled=true;try{await action({action:'approve',batchId:review.batchId,sourceId:review.source_id,approved:!review.approved});review.approved=!review.approved;button.textContent=review.approved?'Retirar aprovação':'Marcar como aprovado';$('#review-message').textContent=review.approved?'Aprovado. Pronto para baixar e publicar por conta própria.':'Voltou para revisão.';await refresh();}catch(e){$('#review-message').textContent=e.message;}finally{button.disabled=false;}});
const posters=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){const v=e.target as HTMLVideoElement;v.src=v.dataset.src;v.load();posters.unobserve(v);}}, {rootMargin:'100px'});
function render(){
 const all=batches.flatMap(b=>b.items),ready=all.filter(i=>i.status==='completed');$('#ready-count').textContent=String(ready.length);$('#review-count').textContent=String(ready.filter(i=>!i.approved).length);$('#approved-count').textContent=String(ready.filter(i=>i.approved).length);
 const list=$('#batch-list');posters.disconnect();list.replaceChildren();let shown=0;
 for(const b of batches){const items=b.items.map((item,index)=>({item,index})).filter(({item:i})=>filter.value==='all'||(filter.value==='review'?i.status==='completed'&&!i.approved:i.status==='completed'&&i.approved));if(!items.length)continue;shown++;
 const section=node('section','','batch-card');section.id='batch-'+b.id;const header=node('div','','batch-heading'),heading=node('div');const ready=b.items.filter(i=>i.status==='completed').length;heading.append(node('h2',b.name),node('p',`${b.recipe.template?.name||'Sem template'} · ${ready}/${b.items.length} prontos`));header.append(heading);const controls=node('div','','batch-controls');const labels={running:'Em produção',completed:'Concluído',partial:'Há pendências',interrupted:'Interrompido'};controls.append(node('span',labels[b.status]||b.status,'batch-state '+b.status));if(ready)controls.append(link('↓ Baixar lote (.zip)','/api/export?batch='+b.id));if(['partial','interrupted'].includes(b.status)){const retry=node('button','Retomar pendentes','ui-button');retry.addEventListener('click',async()=>{(retry as HTMLButtonElement).disabled=true;try{await action({action:'retry',id:b.id});await refresh();}catch(e){$('#message').textContent=e.message;(retry as HTMLButtonElement).disabled=false;}});controls.append(retry);}header.append(controls);section.append(header);
 const grid=node('div','','creative-grid');for(const {item,index} of items){const card=node('article','','creative-card');if(item.status==='completed'){const watch=node('button','','creative-poster');watch.setAttribute('aria-label',`Revisar criativo ${index+1} de ${b.name}`);const video=document.createElement('video');video.muted=true;video.playsInline=true;video.preload='metadata';video.dataset.src='/api/media?kind=clip&id='+item.clip_id+'#t=0.5';video.setAttribute('aria-hidden','true');watch.append(video,node('span','▶ Revisar vídeo','poster-label'));watch.addEventListener('click',()=>openReview(b,item,index));card.append(watch);posters.observe(video);}
 const content=node('div','','creative-content');content.append(node('span',item.status==='completed'?(item.approved?'✓ Aprovado':'Para revisar'):item.status==='rendering'?'Em produção':item.status==='failed'?'Falha':'Na fila','creative-state '+(item.approved?'approved':item.status)),node('h3',`Criativo ${index+1}`),node('p',`@${item.profile||'perfil'}${item.duration?' · '+Math.round(item.duration)+' segundos':''}`));if(item.error)content.append(node('p',item.error,'error'));if(item.status==='rendering'){const progress=document.createElement('progress');progress.max=100;progress.value=item.progress||0;content.append(progress);}
 if(item.status==='completed'){const actions=node('div','','creative-actions');actions.append(link('Ajustar no editor',editUrl(b,item)),link('↓ Baixar vídeo','/api/media?kind=clip&id='+item.clip_id+'&download=1','ui-button ghost'));content.append(actions);}card.append(content);grid.append(card);}section.append(grid);list.append(section);
 }
 if(!shown){const empty=node('div','','creative-empty');empty.append(node('h2',batches.length?'Nenhum criativo neste filtro.':'Seu primeiro criativo começa no Editor.'),node('p',batches.length?'Escolha outro filtro para ver sua produção.':'Ajuste um vídeo e use “Salvar em Criativos”, ou aplique o modelo a um lote.'));list.append(empty);}
}
async function refresh(){try{const r=await fetch('/api/creatives'),data=await r.json();if(!r.ok)throw Error(data.error);batches=data.batches;const next=JSON.stringify(batches);if(next===signature)return;signature=next;render();}catch(e){$('#message').textContent=e.message;}}
filter.addEventListener('change',render);refresh();setInterval(refresh,2500);
