import {initBatchEditor} from './batch-editor';
import {initializeTemplates,drawComposition,templatePayload,templateReady,templateDescription,restoreTemplate} from './templates';
const $=(s:string)=>document.querySelector(s) as HTMLElement;
const input=(s:string)=>$(s) as HTMLInputElement;
const video=$('#preview') as HTMLVideoElement, canvas=$('#result-preview') as HTMLCanvasElement;
const select=$('#source') as HTMLSelectElement, overlay=$('#overlay'), box=$('#selection');
const presetSelect=$('#presets') as HTMLSelectElement;
type Crop={x:number,y:number,width:number,height:number};
let source:any=null,crop:Crop={x:0,y:0,width:2,height:2},clips:any[]=[],busy=false,version=0,clipSignature='';
let presets:any[]=[];try{presets=JSON.parse(localStorage.getItem('dark-crop-presets')||'[]');if(!Array.isArray(presets))presets=[];}catch{}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const even=(v:number)=>Math.floor(v/2)*2;
const fmt=(v:number)=>Number.isFinite(v)?`${Math.floor(v/60)}:${(v%60).toFixed(1).padStart(4,'0')}`:'—';
function message(s:string,error=false){$('#message').textContent=s;$('#message').classList.toggle('error',error);}
function valid(){return source&&Object.values(crop).every(Number.isInteger)&&crop.x>=0&&crop.y>=0&&crop.width>=2&&crop.height>=2&&crop.x+crop.width<=source.width&&crop.y+crop.height<=source.height;}
function normalize(c:Crop):Crop{const w=even(source.width),h=even(source.height);return {x:clamp(even(c.x),0,w-2),y:clamp(even(c.y),0,h-2),width:clamp(even(c.width),2,w-clamp(even(c.x),0,w-2)),height:clamp(even(c.height),2,h-clamp(even(c.y),0,h-2))};}
function draw(){drawComposition(video,crop,!!valid());if(!valid()||video.readyState<2)return;const scale=Math.min(1,420/crop.width,240/crop.height);canvas.width=Math.max(1,Math.round(crop.width*scale));canvas.height=Math.max(1,Math.round(crop.height*scale));canvas.getContext('2d')!.drawImage(video,crop.x,crop.y,crop.width,crop.height,0,0,canvas.width,canvas.height);}
function saveDraft(){if(!source||!valid())return;try{localStorage.setItem(`dark-crop:${source.id}`,JSON.stringify({crop,title:input('#title').value,muted:input('#muted').checked}));}catch{}}
function update(syncInputs=true){
 if(source){box.style.left=`${crop.x/source.width*100}%`;box.style.top=`${crop.y/source.height*100}%`;box.style.width=`${crop.width/source.width*100}%`;box.style.height=`${crop.height/source.height*100}%`;if(syncInputs)for(const k of ['x','y','width','height'])input('#'+k).value=String(crop[k]);
 $('#output-meta').textContent=valid()?`${crop.width} × ${crop.height} px · ${fmt(source.duration)} · duração inteira`:'Seleção fora dos limites da imagem';}
 const rendering=clips.some(c=>c.status==='rendering');const button=$('#export') as HTMLButtonElement;button.disabled=busy||rendering||!templateReady()||!valid()||!input('#title').value.trim();const composed=$('#export-composition') as HTMLButtonElement;composed.disabled=button.disabled||!templatePayload();for(const id of ['#apply-others','#apply-others-crop'])($(id) as HTMLButtonElement).disabled=busy||!valid()||!templateReady();button.textContent=busy?'Preparando…':rendering?'Exportação em andamento…':templatePayload()?'Exportar composição ↗':'Exportar vídeo ↗';video.muted=input('#muted').checked;draw();saveDraft();
}
function fit(){if(!source)return;const area=$('.canvas-wrap');const w=area.clientWidth-32,h=area.clientHeight-32,scale=Math.min(w/source.width,h/source.height);$('#frame').style.width=`${source.width*scale}px`;$('#frame').style.height=`${source.height*scale}px`;}
new ResizeObserver(fit).observe($('.canvas-wrap'));
async function openSource(id:string,restore:any=null){const request=++version;video.pause();source=null;update();try{
 const r=await fetch('/api/editor?source='+encodeURIComponent(id)),data=await r.json();if(!r.ok)throw Error(data.error);if(request!==version)return;source=data;select.value=id;
 let draft=restore;try{draft??=JSON.parse(localStorage.getItem(`dark-crop:${id}`)||'null');}catch{}
 crop=normalize(draft?.crop&&Object.values(draft.crop).every(Number.isFinite)?draft.crop:{x:0,y:0,width:data.width,height:data.height});input('#title').value=draft?.title||`Gameplay de @${data.profile}`;input('#muted').checked=!!draft?.muted;
 video.src='/api/media?id='+encodeURIComponent(id);video.load();input('#seek').max=String(data.duration);input('#seek').value='0';$('#source-meta').textContent=`Original: ${data.width} × ${data.height} · ${fmt(data.duration)}`;fit();update();message('');history.replaceState(null,'','/editor?video='+encodeURIComponent(id));
 }catch(e){if(request!==version)return;source=null;message(e.message,true);update();}}
select.addEventListener('change',()=>openSource(select.value));
video.addEventListener('loadeddata',()=>{$('#time').textContent=`${fmt(video.currentTime)} / ${fmt(source?.duration)}`;draw();});video.addEventListener('seeked',draw);
video.addEventListener('error',()=>message('Não foi possível abrir o vídeo do acervo.',true));
video.addEventListener('timeupdate',()=>{input('#seek').value=String(video.currentTime);$('#time').textContent=`${fmt(video.currentTime)} / ${fmt(source?.duration)}`;draw();});
video.addEventListener('pause',()=>$('#play').textContent='▶ Reproduzir');video.addEventListener('play',()=>{$('#play').textContent='Ⅱ Pausar';const tick=()=>{draw();if(!video.paused&&!video.ended)requestAnimationFrame(tick);};requestAnimationFrame(tick);});
$('#play').addEventListener('click',()=>{if(!source)return;if(video.paused)video.play().catch(()=>message('Não foi possível iniciar a reprodução.',true));else video.pause();});
input('#seek').addEventListener('input',()=>{if(source)video.currentTime=Number(input('#seek').value);});
for(const k of ['x','y','width','height'])input('#'+k).addEventListener('input',()=>{crop[k]=input('#'+k).value===''?NaN:Number(input('#'+k).value);update(false);});
for(const k of ['#title','#muted'])input(k).addEventListener('input',()=>update(false));
$('#reset').addEventListener('click',()=>{if(!source)return;crop=normalize({x:0,y:0,width:source.width,height:source.height});update();});
let drag:any=null;
function point(e:PointerEvent){const r=overlay.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width*source.width,0,source.width),y:clamp((e.clientY-r.top)/r.height*source.height,0,source.height)};}
overlay.addEventListener('pointerdown',e=>{if(!source||e.button!==0)return;e.preventDefault();video.pause();if(!valid())crop=normalize({x:0,y:0,width:source.width,height:source.height});const p=point(e),target=e.target as HTMLElement;drag={id:e.pointerId,p,original:{...crop},mode:target.dataset.handle||(box.contains(target)?'move':'draw')};overlay.setPointerCapture(e.pointerId);});
overlay.addEventListener('pointermove',e=>{if(!drag||!source||e.pointerId!==drag.id)return;const p=point(e),o=drag.original,dx=p.x-drag.p.x,dy=p.y-drag.p.y;let c:Crop;
 if(drag.mode==='move')c={...o,x:clamp(o.x+dx,0,source.width-o.width),y:clamp(o.y+dy,0,source.height-o.height)};
 else {let ax:number,ay:number,bx:number,by:number;if(drag.mode==='draw'){ax=drag.p.x;ay=drag.p.y;bx=p.x;by=p.y;}else{ax=drag.mode.includes('w')?o.x+o.width:o.x;ay=drag.mode.includes('n')?o.y+o.height:o.y;bx=p.x;by=p.y;}c={x:Math.min(ax,bx),y:Math.min(ay,by),width:Math.abs(bx-ax),height:Math.abs(by-ay)};}
 crop=normalize(c);update();});
for(const event of ['pointerup','pointercancel'])overlay.addEventListener(event,()=>{drag=null;});
box.addEventListener('keydown',e=>{if(!source||!valid())return;const delta=e.shiftKey?10:2;const moves={ArrowLeft:[-delta,0],ArrowRight:[delta,0],ArrowUp:[0,-delta],ArrowDown:[0,delta]};if(!moves[e.key])return;e.preventDefault();const [x,y]=moves[e.key];crop=normalize({...crop,x:clamp(crop.x+x,0,source.width-crop.width),y:clamp(crop.y+y,0,source.height-crop.height)});update();});
function renderPresets(){presetSelect.replaceChildren(new Option('Escolha um modelo salvo',''));presets.forEach((p,i)=>presetSelect.add(new Option(p.name,String(i))));}
$('#save-preset').addEventListener('click',()=>{if(!valid()||!input('#title').value.trim())return;const p={name:input('#title').value.trim(),crop:{x:crop.x/source.width,y:crop.y/source.height,width:crop.width/source.width,height:crop.height/source.height}};presets.push(p);try{localStorage.setItem('dark-crop-presets',JSON.stringify(presets));renderPresets();presetSelect.value=String(presets.length-1);message('Seleção salva como modelo neste navegador.');}catch{presets.pop();message('Não foi possível salvar o modelo neste navegador.',true);}});
$('#apply-preset').addEventListener('click',()=>{if(!source||presetSelect.value==='')return;const p=presets[Number(presetSelect.value)]?.crop;if(!p||!['x','y','width','height'].every(k=>Number.isFinite(p[k])))return;crop=normalize({x:p.x*source.width,y:p.y*source.height,width:p.width*source.width,height:p.height*source.height});update();message('Modelo aplicado. Confira a área selecionada neste vídeo antes de exportar.');});
$('#crop-form').addEventListener('submit',async e=>{e.preventDefault();if(!valid()||busy)return;busy=true;video.pause();update();try{crop=normalize(crop);update();const r=await fetch('/api/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceId:source.id,title:input('#title').value,crop,muted:input('#muted').checked,template:templatePayload()})}),data=await r.json();if(!r.ok)throw Error(data.error);message('Exportação iniciada com a duração inteira. Acompanhe abaixo.');await refresh();}catch(e){message(e.message,true);}finally{busy=false;update();}});
const dialog=$('#result-dialog') as HTMLDialogElement,resultVideo=$('#result-video') as HTMLVideoElement;
$('#close-result').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{resultVideo.pause();resultVideo.removeAttribute('src');resultVideo.load();});
function node(tag:string,text:string,cls=''){const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;}
async function refresh(){try{const r=await fetch('/api/editor'),data=await r.json();if(!r.ok)throw Error(data.error);clips=data.clips;const signature=JSON.stringify(clips);if(signature!==clipSignature){clipSignature=signature;const list=$('#exports-list');list.replaceChildren();if(!clips.length)list.append(node('p','Suas exportações vão aparecer aqui.'));for(const clip of clips){const row=node('article','','export-row'),info=node('div','','export-info');info.append(node('h3',clip.title),node('p',`${clip.template_json?`${JSON.parse(clip.template_json).name} · composição`:clip.crop_w?`${clip.crop_w} × ${clip.crop_h} · imagem selecionada`:'Exportação antiga por tempo'} · ${fmt(clip.end-clip.start)} · ${clip.status==='completed'?'Pronto':clip.status==='rendering'?`Exportando ${clip.progress}%`:clip.error||'Interrompido'}`));row.append(info);if(clip.status==='rendering'){const p=document.createElement('progress');p.max=100;p.value=clip.progress;row.append(p);}if(clip.status==='completed'){const view=node('button','Ver');view.addEventListener('click',()=>{$('#result-title').textContent=clip.title;resultVideo.src='/api/media?kind=clip&id='+clip.id;($('#result-download') as HTMLAnchorElement).href=resultVideo.src+'&download=1';dialog.showModal();});const link=node('a','↓ Baixar') as HTMLAnchorElement;link.href='/api/media?kind=clip&id='+clip.id+'&download=1';row.append(view,link);}if(clip.crop_w){const edit=node('button','Abrir seleção');edit.addEventListener('click',()=>{restoreTemplate(clip.template_json?JSON.parse(clip.template_json):null);openSource(clip.source_id,{crop:{x:clip.crop_x,y:clip.crop_y,width:clip.crop_w,height:clip.crop_h},title:clip.title,muted:!!clip.muted});$('.editor-grid').scrollIntoView({block:'start'});});row.append(edit);}list.append(row);}}update(false);}catch(e){message(e.message,true);}}
async function init(){await initializeTemplates(()=>update(false));renderPresets();try{const r=await fetch('/api/library'),data=await r.json();if(!r.ok)throw Error(data.error);const videos=data.videos.filter(v=>v.status==='downloaded');select.replaceChildren();for(const v of videos)select.add(new Option(`@${v.profile} · ${(v.caption||v.id).slice(0,100)}`,v.id));if(videos.length){const id=new URLSearchParams(location.search).get('video');await openSource(videos.some(v=>v.id===id)?id:videos[0].id);}else{select.disabled=true;message('Adicione um vídeo à biblioteca para começar.');}}catch(e){message(e.message,true);}await refresh();}
initBatchEditor(()=>valid()&&templateReady()?{normalizedCrop:{x:crop.x/source.width,y:crop.y/source.height,width:crop.width/source.width,height:crop.height/source.height},muted:input('#muted').checked,template:templatePayload()}:null);
init();setInterval(refresh,2500);
